// <auto-generated />
using System;
using KhumaloCraft2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KhumaloCraft2.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240527131211_Total")]
    partial class Total
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KhumaloCraft2.Models.ArtWork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CatID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .IsRequired()
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProdName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ArtWorks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Artist = "Khumalo",
                            Availability = "Available",
                            CatID = 0,
                            Description = "A vibrant abstract painting featuring bold, overlapping geometric shapes and vivid colors. The dynamic composition and contrasting hues create a sense of movement and depth, evoking strong emotions and inviting viewers to interpret the scene in their own unique way.",
                            ImageFileName = "Piccasso.jpg.png",
                            Price = 250000m,
                            ProdName = "Piccasso",
                            Quantity = 1,
                            Type = "Painting"
                        },
                        new
                        {
                            Id = 2,
                            Artist = "Van Gogh",
                            Availability = "Available",
                            CatID = 0,
                            Description = "A serene landscape painting depicting a tranquil sunset over a calm lake. Soft, warm hues blend seamlessly in the sky, reflecting beautifully on the water’s surface. Silhouetted trees along the shore add depth and balance to the peaceful scene.",
                            ImageFileName = "StarringNight.jpg.png",
                            Price = 55502m,
                            ProdName = "Starring Night",
                            Quantity = 1,
                            Type = "Painting"
                        },
                        new
                        {
                            Id = 3,
                            Artist = "Monet",
                            Availability = "Available",
                            CatID = 0,
                            Description = "Fine work of art from France",
                            ImageFileName = "Lumiere.jpg.png",
                            Price = 6500m,
                            ProdName = "Lumiere",
                            Quantity = 3,
                            Type = "Painting"
                        },
                        new
                        {
                            Id = 4,
                            Artist = "Khumalo",
                            Availability = "Available",
                            CatID = 0,
                            Description = "A powerful painting capturing the essence of African struggle, with strong, expressive figures set against a stark, tumultuous backdrop. Earthy tones and bold strokes convey resilience and determination, while symbolic elements highlight the rich cultural heritage and enduring spirit of the people.",
                            ImageFileName = "Amandla.jpg.png",
                            Price = 5302m,
                            ProdName = "Amandla",
                            Quantity = 3,
                            Type = "Painting"
                        },
                        new
                        {
                            Id = 5,
                            Artist = "Smith",
                            Availability = "Available",
                            CatID = 0,
                            Description = "A breathtaking photo of the Swiss Alps, showcasing majestic snow-capped peaks under a clear blue sky. Lush green valleys and sparkling alpine lakes contrast beautifully with the rugged mountain terrain, creating a stunning and serene natural landscape.",
                            ImageFileName = "Sky.jpg.png",
                            Price = 345m,
                            ProdName = "Sky",
                            Quantity = 8,
                            Type = "Photos"
                        },
                        new
                        {
                            Id = 6,
                            Artist = "John",
                            Availability = "Available",
                            CatID = 0,
                            Description = "A compelling photo of a South African township, capturing vibrant, colorful homes packed closely together. The lively streets are filled with activity, reflecting the resilience and community spirit of the residents. In the background, sprawling urban landscapes contrast with the nearby natural beauty.",
                            ImageFileName = "Kasi.jpg.png",
                            Price = 100m,
                            ProdName = "Kasi",
                            Quantity = 10,
                            Type = "Photos"
                        },
                        new
                        {
                            Id = 7,
                            Artist = "Morris",
                            Availability = "Available",
                            CatID = 0,
                            Description = "A magnificent polar bear, standing tall against a backdrop of pristine Arctic ice. Its thick, white fur glistens in the sunlight, blending seamlessly with the icy surroundings. With powerful limbs and sharp claws, it exudes strength and grace, a true master of its frozen domain.",
                            ImageFileName = "PolarBear.jpg.png",
                            Price = 250m,
                            ProdName = "Polar Bear",
                            Quantity = 8,
                            Type = "Photos"
                        },
                        new
                        {
                            Id = 8,
                            Artist = "Dory",
                            Availability = "Available",
                            CatID = 0,
                            Description = "A colorful coral reef alive with marine creatures, swaying gently in the clear turquoise waters.",
                            ImageFileName = "CoralReef.jpg.png",
                            Price = 2345m,
                            ProdName = "Coral Reef",
                            Quantity = 5,
                            Type = "Photos"
                        },
                        new
                        {
                            Id = 9,
                            Artist = "Khumalo",
                            Availability = "Available",
                            CatID = 0,
                            Description = "A dazzling crystal sculpture, intricately crafted to capture and reflect light with stunning precision.",
                            ImageFileName = "Crystal.jpg.png",
                            Price = 2010m,
                            ProdName = "Crystal",
                            Quantity = 4,
                            Type = "Sculpture"
                        },
                        new
                        {
                            Id = 10,
                            Artist = "Khumalo",
                            Availability = "Available",
                            CatID = 0,
                            Description = "A majestic elephant sculpture, crafted with lifelike detail and grace, capturing the essence of these gentle giants in a stunning work of art.",
                            ImageFileName = "Elephant.jpg.png",
                            Price = 550m,
                            ProdName = "Elephant",
                            Quantity = 8,
                            Type = "Sculpture"
                        },
                        new
                        {
                            Id = 11,
                            Artist = "Khumalo",
                            Availability = "Available",
                            CatID = 0,
                            Description = "An African doll, beautifully handcrafted with vibrant fabrics and intricate beadwork, representing the rich cultural heritage and artistic traditions of the continent.",
                            ImageFileName = "/images/AfricanDoll.jpg.png",
                            Price = 610m,
                            ProdName = "African Doll",
                            Quantity = 12,
                            Type = "Sculpture"
                        },
                        new
                        {
                            Id = 12,
                            Artist = "Khumalo",
                            Availability = "Available",
                            CatID = 0,
                            Description = "A human sculpture serving as furniture, blending artistry with functionality seamlessly.",
                            ImageFileName = "Human.jpg.png",
                            Price = 34010m,
                            ProdName = "Human",
                            Quantity = 2,
                            Type = "Sculpture"
                        },
                        new
                        {
                            Id = 13,
                            Artist = "Serenity Maker",
                            Availability = "Available",
                            CatID = 0,
                            Description = "A delicate ceramic bowl with a serene blue glaze, reminiscent of tranquil ocean waters. Its smooth curves and gentle ripples evoke a sense of calm and relaxation.",
                            ImageFileName = "SerenityBowl.jpg.png",
                            Price = 670m,
                            ProdName = "Serenity Bowl",
                            Quantity = 21,
                            Type = "Ceramics"
                        },
                        new
                        {
                            Id = 14,
                            Artist = "Khumalo",
                            Availability = "Available",
                            CatID = 0,
                            Description = "A rustic ceramic mug with a rich, earthy glaze reminiscent of glowing embers. Its sturdy handle and textured surface provide a cozy and comforting feel, perfect for enjoying a warm beverage on a chilly evening.",
                            ImageFileName = "EmberMug.jpg.png",
                            Price = 310m,
                            ProdName = "Ember Mug",
                            Quantity = 12,
                            Type = "Ceramics"
                        },
                        new
                        {
                            Id = 15,
                            Artist = "Whisper Maker",
                            Availability = "Available",
                            CatID = 0,
                            Description = "A slender ceramic vase with a soft, matte finish, exuding elegance and understated beauty. Its graceful silhouette and muted tones create a sense of tranquility, making it ideal for showcasing delicate blooms.",
                            ImageFileName = "WhisperVase.jpg.png",
                            Price = 200m,
                            ProdName = "Whisper Vase",
                            Quantity = 4,
                            Type = "Ceramics"
                        },
                        new
                        {
                            Id = 16,
                            Artist = "Owami",
                            Availability = "Available",
                            CatID = 0,
                            Description = "A charming ceramic teapot adorned with intricate floral motifs, echoing the beauty of nature. Its generous size and graceful spout make it both functional and decorative, adding a touch of whimsy to tea time.",
                            ImageFileName = "EchoTeapot.jpg.png",
                            Price = 450m,
                            ProdName = "Echo Teapot",
                            Quantity = 8,
                            Type = "Ceramics"
                        });
                });

            modelBuilder.Entity("KhumaloCraft2.Models.Category", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CatId"));

                    b.Property<string>("CatName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CatId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CatId = 1,
                            CatName = "Paintings"
                        },
                        new
                        {
                            CatId = 2,
                            CatName = "Photos"
                        },
                        new
                        {
                            CatId = 3,
                            CatName = "Sculptures"
                        },
                        new
                        {
                            CatId = 4,
                            CatName = "Ceramics"
                        });
                });

            modelBuilder.Entity("KhumaloCraft2.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Group");
                });

            modelBuilder.Entity("KhumaloCraft2.Models.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CatId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .IsRequired()
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProdName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("CatId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Artist = "Khumalo",
                            Availability = "Available",
                            CatId = 1,
                            Description = "A vibrant abstract painting featuring bold, overlapping geometric shapes and vivid colors. The dynamic composition and contrasting hues create a sense of movement and depth, evoking strong emotions and inviting viewers to interpret the scene in their own unique way.",
                            ImageFileName = "Piccasso.jpg.png",
                            Price = 250000m,
                            ProdName = "Piccasso",
                            Quantity = 1
                        },
                        new
                        {
                            id = 2,
                            Artist = "Van Gogh",
                            Availability = "Available",
                            CatId = 1,
                            Description = "A serene landscape painting depicting a tranquil sunset over a calm lake. Soft, warm hues blend seamlessly in the sky, reflecting beautifully on the water’s surface. Silhouetted trees along the shore add depth and balance to the peaceful scene.",
                            ImageFileName = "StarringNight.jpg.png",
                            Price = 55502m,
                            ProdName = "Starring Night",
                            Quantity = 1
                        },
                        new
                        {
                            id = 3,
                            Artist = "Monet",
                            Availability = "Available",
                            CatId = 1,
                            Description = "Fine work of art from France",
                            ImageFileName = "Lumiere.jpg.png",
                            Price = 6500m,
                            ProdName = "Lumiere",
                            Quantity = 3
                        },
                        new
                        {
                            id = 4,
                            Artist = "Khumalo",
                            Availability = "Available",
                            CatId = 1,
                            Description = "A powerful painting capturing the essence of African struggle, with strong, expressive figures set against a stark, tumultuous backdrop. Earthy tones and bold strokes convey resilience and determination, while symbolic elements highlight the rich cultural heritage and enduring spirit of the people.",
                            ImageFileName = "Amandla.jpg.png",
                            Price = 5302m,
                            ProdName = "Amandla",
                            Quantity = 3
                        },
                        new
                        {
                            id = 5,
                            Artist = "Smith",
                            Availability = "Available",
                            CatId = 2,
                            Description = "A breathtaking photo of the Swiss Alps, showcasing majestic snow-capped peaks under a clear blue sky. Lush green valleys and sparkling alpine lakes contrast beautifully with the rugged mountain terrain, creating a stunning and serene natural landscape.",
                            ImageFileName = "Sky.jpg.png",
                            Price = 345m,
                            ProdName = "Sky",
                            Quantity = 8
                        },
                        new
                        {
                            id = 6,
                            Artist = "John",
                            Availability = "Available",
                            CatId = 2,
                            Description = "A compelling photo of a South African township, capturing vibrant, colorful homes packed closely together. The lively streets are filled with activity, reflecting the resilience and community spirit of the residents. In the background, sprawling urban landscapes contrast with the nearby natural beauty.",
                            ImageFileName = "Kasi.jpg.png",
                            Price = 100m,
                            ProdName = "Kasi",
                            Quantity = 10
                        },
                        new
                        {
                            id = 7,
                            Artist = "Morris",
                            Availability = "Available",
                            CatId = 2,
                            Description = "A magnificent polar bear, standing tall against a backdrop of pristine Arctic ice. Its thick, white fur glistens in the sunlight, blending seamlessly with the icy surroundings. With powerful limbs and sharp claws, it exudes strength and grace, a true master of its frozen domain.",
                            ImageFileName = "PolarBear.jpg.png",
                            Price = 250m,
                            ProdName = "Polar Bear",
                            Quantity = 8
                        },
                        new
                        {
                            id = 8,
                            Artist = "Dory",
                            Availability = "Available",
                            CatId = 2,
                            Description = "A colorful coral reef alive with marine creatures, swaying gently in the clear turquoise waters.",
                            ImageFileName = "CoralReef.jpg.png",
                            Price = 2345m,
                            ProdName = "Coral Reef",
                            Quantity = 5
                        },
                        new
                        {
                            id = 9,
                            Artist = "Khumalo",
                            Availability = "Available",
                            CatId = 3,
                            Description = "A dazzling crystal sculpture, intricately crafted to capture and reflect light with stunning precision.",
                            ImageFileName = "Crystal.jpg.png",
                            Price = 2010m,
                            ProdName = "Crystal",
                            Quantity = 4
                        },
                        new
                        {
                            id = 10,
                            Artist = "Khumalo",
                            Availability = "Available",
                            CatId = 3,
                            Description = "A majestic elephant sculpture, crafted with lifelike detail and grace, capturing the essence of these gentle giants in a stunning work of art.",
                            ImageFileName = "Elephant.jpg.png",
                            Price = 550m,
                            ProdName = "Elephant",
                            Quantity = 8
                        },
                        new
                        {
                            id = 11,
                            Artist = "Khumalo",
                            Availability = "Available",
                            CatId = 3,
                            Description = "An African doll, beautifully handcrafted with vibrant fabrics and intricate beadwork, representing the rich cultural heritage and artistic traditions of the continent.",
                            ImageFileName = "AfricanDoll.jpg.png",
                            Price = 610m,
                            ProdName = "African Doll",
                            Quantity = 12
                        },
                        new
                        {
                            id = 12,
                            Artist = "Khumalo",
                            Availability = "Available",
                            CatId = 3,
                            Description = "A human sculpture serving as furniture, blending artistry with functionality seamlessly.",
                            ImageFileName = "Human.jpg.png",
                            Price = 34010m,
                            ProdName = "Human",
                            Quantity = 2
                        },
                        new
                        {
                            id = 13,
                            Artist = "Serenity Maker",
                            Availability = "Available",
                            CatId = 4,
                            Description = "A delicate ceramic bowl with a serene blue glaze, reminiscent of tranquil ocean waters. Its smooth curves and gentle ripples evoke a sense of calm and relaxation.",
                            ImageFileName = "SerenityBowl.jpg.png",
                            Price = 670m,
                            ProdName = "Serenity Bowl",
                            Quantity = 21
                        },
                        new
                        {
                            id = 14,
                            Artist = "Khumalo",
                            Availability = "Available",
                            CatId = 4,
                            Description = "A rustic ceramic mug with a rich, earthy glaze reminiscent of glowing embers. Its sturdy handle and textured surface provide a cozy and comforting feel, perfect for enjoying a warm beverage on a chilly evening.",
                            ImageFileName = "EmberMug.jpg.png",
                            Price = 310m,
                            ProdName = "Ember Mug",
                            Quantity = 12
                        },
                        new
                        {
                            id = 15,
                            Artist = "Whisper Maker",
                            Availability = "Available",
                            CatId = 4,
                            Description = "A slender ceramic vase with a soft, matte finish, exuding elegance and understated beauty. Its graceful silhouette and muted tones create a sense of tranquility, making it ideal for showcasing delicate blooms.",
                            ImageFileName = "WhisperVase.jpg.png",
                            Price = 200m,
                            ProdName = "Whisper Vase",
                            Quantity = 4
                        },
                        new
                        {
                            id = 16,
                            Artist = "Owami",
                            Availability = "Available",
                            CatId = 4,
                            Description = "A charming ceramic teapot adorned with intricate floral motifs, echoing the beauty of nature. Its generous size and graceful spout make it both functional and decorative, adding a touch of whimsy to tea time.",
                            ImageFileName = "EchoTeapot.jpg.png",
                            Price = 450m,
                            ProdName = "Echo Teapot",
                            Quantity = 8
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("KhumaloCraft2.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("KhumaloCraft2.Models.Product", b =>
                {
                    b.HasOne("KhumaloCraft2.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
